# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(default='idle', max_length=50)),
                ('current_task', models.TextField(blank=True, default='')),
                ('progress', models.IntegerField(default=0)),
                ('confidence', models.IntegerField(default=90)),
                ('evidence_analyzed', models.IntegerField(default=0)),
                ('findings', models.IntegerField(default=0)),
                ('color', models.CharField(default='#2563eb', max_length=50)),
                ('icon', models.CharField(default='Cpu', max_length=50)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(default='info', max_length=50)),
                ('time', models.CharField(blank=True, default='', max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('investigation_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
