# Generated by Django 5.2.17 on 2026-08-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50)),
                ('type', models.CharField(default='general', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('REVIEW', 'Review'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('planning', 'Planning'), ('collecting', 'Collecting'), ('processing', 'Processing'), ('analyzing', 'Analyzing'), ('reporting', 'Reporting'), ('complete', 'Complete')], default='planning', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('trust_score', models.IntegerField(default=90)),
                ('confidence', models.IntegerField(default=85)),
                ('progress', models.IntegerField(default=0)),
                ('evidence_count', models.IntegerField(default=0)),
                ('agents_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='investigator', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dfiruser')),
            ],
            options={
                'db_table': 'case_members',
                'unique_together': {('case', 'user')},
            },
        ),
    ]
