# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('evidence_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('timestamp', models.CharField(db_index=True, max_length=100)),
                ('timestamp_precision', models.CharField(default='exact', max_length=50)),
                ('type', models.CharField(choices=[('login', 'Login'), ('file-create', 'File Create'), ('file-delete', 'File Delete'), ('usb-event', 'USB Event'), ('registry-change', 'Registry Change'), ('browser', 'Browser Activity'), ('malware', 'Malware Execution'), ('cloud', 'Cloud Activity'), ('auth', 'Authentication'), ('network', 'Network Connection'), ('process', 'Process Creation')], default='file-create', max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['timestamp'],
            },
        ),
    ]
