# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('job_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('evidence_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('job_type', models.CharField(default='artifact_extraction', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-started_at'],
            },
        ),
    ]
