# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('investigation_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('hash_md5', models.CharField(blank=True, default='', max_length=64)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('hash_sha512', models.CharField(blank=True, default='', max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.CharField(blank=True, default='', max_length=255)),
                ('trust_score', models.IntegerField(default=95)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('analyzed', 'Analyzed'), ('error', 'Error'), ('INTEGRITY_COMPROMISED', 'Integrity Compromised')], default='verified', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
