# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=50)),
                ('confidence', models.IntegerField(default=90)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('agent_id', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
