# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DFIRUser',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('investigator', 'Investigator'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='investigator', max_length=50)),
                ('avatar', models.URLField(blank=True, default='')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DFIR User',
                'verbose_name_plural': 'DFIR Users',
                'db_table': 'dfir_users',
            },
        ),
    ]
