# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(db_index=True, max_length=64)),
                ('case_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('ACQUIRED', 'Acquired'), ('UPLOADED', 'Uploaded'), ('ACCESSED', 'Accessed'), ('COPIED', 'Copied'), ('PROCESSED', 'Processed'), ('HASH_VERIFIED', 'Hash Verified'), ('INTEGRITY_FAILURE', 'Integrity Failure'), ('EXPORTED', 'Exported'), ('REPORT_GENERATED', 'Report Generated'), ('collected', 'Collected'), ('transferred', 'Transferred'), ('analyzed', 'Analyzed'), ('verified', 'Verified')], default='ACQUIRED', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='System', max_length=255)),
                ('location', models.CharField(default='Secure Storage', max_length=255)),
                ('hash', models.CharField(blank=True, default='', max_length=128)),
                ('signature', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'chain_of_custody',
                'ordering': ['timestamp'],
            },
        ),
    ]
