# Generated by Django 5.2.17 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReport',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(choices=[('executive', 'Executive Summary'), ('technical', 'Technical Report'), ('legal', 'Legal / Chain of Custody Report')], default='technical', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('complete', 'Complete'), ('error', 'Error')], default='complete', max_length=50)),
                ('confidence', models.IntegerField(default=95)),
                ('sections', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'forensic_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
